defaults:
  - u2d2: leader_id1
  - hand_config: ditto_2f_leader_only
  - motor_models: default
  - joint_configs: default
  - sharpa: default
  - _self_

control_frequency: 200
verbose: false
show_current_breakdown: false
show_perf: false
